### ISSUE TITLE
Clear answer on tools when input changes ... or not

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-tools#107]
Right now the rate spread and check digit tools act differently when input changes after an answer has been given to a previous submission.

The check digit clears any answer when the inputs change. The rate spread does not.

I prefer clearing answers if inputs change to avoid any confusion about which data was used to get the answer but would like to hear what others think.

@designlanguage @wpears @keileyo

**Comment by wpears** [comment]
Something else we could do is embed the query params into the response alert, so that the Alert has all the info needed to see how the rate spread was derived. We could then even allow calculating multiple rate spreads and keeping the results of each on the page (with maybe a close icon on each alert to clear it).

**Comment by awolfe76** [comment]
I'm not sure we'd need that given that there is a batch too. I think it would be ok to just clear the previous response when we see input updates.

But, this made me think about adding the arguments to the URL ... again not sure if we have this use case but it would be nice to be able to "share" the results this way. 

I created another issue for that just in case - #108.

**Comment by awolfe76** [comment]
Closing. See #99.
