### ISSUE TITLE
Add language on what results in a NA response

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-tools#79]
Instead of adding to the labels on the inputs we should have a message at the top of the form (maybe an alert), saying something like 

"If your Action Taken Type is 3, 4, 5, 6, or 7 __or__ if your Reverse is 1 you should report the Rate Spread as __NA__."

We can then remove those warning from the labels.

We could also just include those options, and if one of them is selected, show the response without making an API call.

**Comment by designlanguage** [comment]
I think an alert or can come up if someone chooses Action Taken Type 3, 4, 5, 6, 7 or Reverse Mortgage 1. It would basically appear as a calculation result with an __NA__ instead of a rate spread, with a description of why "NA" came up. Side note - It's strange to have a radio button for something with no selectable options.

Including adding descriptions (from #85), the radio buttons could be stacked vertically. Something like this:

![screen shot 2018-01-03 at 4 18 51 pm](https://user-images.githubusercontent.com/10562544/34540336-2d5736b4-f0a2-11e7-8d68-32b00540504b.png)

**Comment by awolfe76** [comment]
@designlanguage - I just want to make sure.

Are you saying, if we add all inputs and the user selects one that we know is NA, we would scroll to the answer (like in #89) and display it; without making an API call?

We would just have to make that message clearer in those cases, eg "Your rate spread is NA because you selected 1 (or true) for the reverse mortgage".

**Comment by designlanguage** [comment]
@awolfe76 - That's what I'm thinking, yes.

When it scrolls to the answer, can the user scroll back up and select a different Action Taken Type? If so, what happens then... does the answer disappear?

**Comment by awolfe76** [comment]
Definitely, they can scroll back up and change the form at any time.

I think the answer should disappear if they update the form (created #99). We've done that in the check digit tool.

I think we should add that to the message in these cases, "Your rate spread is NA because you selected 1 (or true) for the reverse mortgage. **Please update the form if you've selected an option incorrectly.**"

_Wording can change, just trying to show what I mean._

**Comment by colleenms** [comment]
Agree with @designlanguage. In the HMDA Help cases, we're seeing that some users are confused by the current radio button for Reverse Mortgage.

It may be helpful if we keep the wording consistent with the FIG, since that is the source of the number codes. 1) Reverse Mortgage, 2) Not a Reverse Mortgage. Also, for the Action Taken Type, Option 1 would read "Loan originated" and Option 2 would read "Application approved but not accepted".
